apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: test-vm-dakota-disk
  namespace: default
spec:
  source:
    registry:
      url: "docker://192.168.1.102:5000/dakota:latest"
      pullMethod: node
  pvc:
    accessModes: [ReadWriteOnce]
    resources:
      requests:
        storage: 50Gi
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: test-vm-dakota
  namespace: default
  labels:
    role: test-vm
    variant: dakota
spec:
  runStrategy: Manual
  template:
    spec:
      domain:
        cpu:
          cores: 8
          sockets: 1
          threads: 1
        memory:
          guest: 8Gi
        devices:
          autoattachGraphicsDevice: true
          disks:
            - name: rootdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
      networks:
        - name: default
          pod: {}
      volumes:
        - name: rootdisk
          dataVolume:
            name: test-vm-dakota-disk
