events {}
http {
    server {
        listen 8090 ssl;
        ssl_certificate     /certs/192.168.1.102+3.pem;
        ssl_certificate_key /certs/192.168.1.102+3-key.pem;
        ssl_protocols       TLSv1.2 TLSv1.3;
        location / {
            proxy_pass http://127.0.0.1:9191;
            proxy_set_header Host $host;
            sub_filter '</head>' '<script>${INIT_SCRIPT}</script></head>';
            sub_filter_once  on;
            sub_filter_types text/html;
        }
    }
}
